# Part 1: basic API tests — fast sanity checks of the public interface
println("========== Part 1: API tests ==========")
include("lattice.jl")
include("integration.jl")
include("correlation.jl")
include("hybriddynamics.jl")
include("sysdynamics.jl")
include("grassmannmps.jl")
include("grassmanntensor.jl")
include("mpo.jl")
include("mult.jl")
include("observables.jl")
include("electronphonon.jl")
